---
#============================ Data
starttime: 2021-12-10T00:00:00
endtime: 2022-01-20T00:00:00
searchWindow: []
# Selected region for downloading stations
center: [56.25, 27.50]
minradius: 0.0
maxradius: 1.0
# Selected region for appyling picker
xlim_degree: [55.00, 58.00]
ylim_degree: [26.00, 29.00]
zlim_degree: [0.0, 50.0]
# Data restriction
networks: [FN, BI]
fdsn_urls: ["http://localhost:8080"]
stations_inv: stations.xml
picks_file: results/picks.csv
preprocess_data: true
#============================ PhaseNet settings
repick_data: true
min_p_prob: 0.3
min_s_prob: 0.3
highpass_filter: 0.0
model: "original"
#============================ GaMMA settings
degree2km: 111.19492474777779
use_dbscan: true
method: BGMM
# Velocity Model, (Acarel et al, 2019)
useEikonal: true
zz: [0.0, 2.0, 4.0, 10.0, 14.0, 19.0, 46.0]
vp: [4.2, 5.4, 5.7,  5.9,  6.1,  6.5,  8.2]
vp_vs_ratio: 1.75
h: 3.0
# DBSCAN
dbscan_eps: 15 # The maximum time between two neighbor picks, A for auto set
dbscan_min_samples: 5 # The number neighbor to be considered as a core point
# Filtering
min_picks_per_eq: 5
min_p_picks_per_eq: 4
min_s_picks_per_eq: 1
max_sigma11: 1.5 # Max phase time residual (s)
max_sigma22: 1.0 # Max phase amplitude residual (in log scale)
max_sigma12: 1.0 # Max covariance term. (Usually not used)
use_amplitude: false
#============================ Visilization
plotResults: true
nTests: 3
minmaxRes: 2.0 # s
maxDist: 75   # km
statisticsBy: "hypocenter"
#============================ Catalog export
outCatFmt: ["NORDIC", "QUAKEML"]
#============================ Cross sections
profiles:
  -
    dx: 5.0
    dy: 20.0
    length: 50.0
    width: 5.0
    z: 30.0
    theta: -30
  -
    dx: 0.0
    dy: 15.0
    length: 50.0
    width: 5.0
    z: 30.0
    theta: -30
  -
    dx: -5.0
    dy: 10.0
    length: 50.0
    width: 5.0
    z: 30.0
    theta: -30
  -
    dx: -10.0
    dy: 5.0
    length: 50.0
    width: 5.0
    z: 30.0
    theta: -30