---
#============================ Data
starttime: 2023-04-01T00:00:00
endtime: 2023-05-01T00:00:00
searchWindow: []
# Selected region for downloading stations
center: [51.00, 29.00]
minradius: 0.0
maxradius: 1.5
# Selected region for appyling picker
xlim_degree: [50.00, 52.00]
ylim_degree: [28.00, 30.00]
zlim_degree: [0.0, 50.0]
# Data restriction
networks: [BP, BI, IR]
fdsn_urls: ["http://localhost:8080"]
stations_inv: stations.xml
picks_file: results/picks.csv
preprocess_data: true
#============================ PhaseNet settings
repick_data: true
min_p_prob: 0.3
min_s_prob: 0.4
highpass_filter: 0.0
model: "original"
#============================ GaMMA settings
degree2km: 111.19492474777779
use_dbscan: true
method: BGMM
# Velocity Model, (Acarel et al, 2019)
useEikonal: true
zz: [0.0, 5.5, 7.0, 11.0]
vp: [3.9, 4.9, 5.7,  6.2]
vp_vs_ratio: 1.81
h: 3.0
# DBSCAN
dbscan_eps: 15 # The maximum time between two neighbor picks
dbscan_min_samples: 3 # The number neighbor to be considered as a core point
# Filtering
min_picks_per_eq: 4
min_p_picks_per_eq: 3
min_s_picks_per_eq: 1
max_sigma11: 1.5 # Max phase time residual (s)
max_sigma22: 1.0 # Max phase amplitude residual (in log scale)
max_sigma12: 1.0 # Max covariance term. (Usually not used)
use_amplitude: false
#============================ Visilization
plotResults: true
nTests: 3
minmaxRes: 2.0 # s
maxDist: 75   # km
statisticsBy: "hypocenter"
#============================ Catalog export
outCatFmt: ["NORDIC", "SC3ML"]
#============================ Cross sections
profiles:
  -
    dx: -5.0
    dy: 15.0
    length: 40.0
    width: 5.0
    z: 30.0
    theta: 0
  -
    dx: -5.0
    dy: 15.0
    length: 50.0
    width: 5.0
    z: 30.0
    theta: 30
  -
    dx: -5.0
    dy: 15.0
    length: 50.0
    width: 5.0
    z: 30.0
    theta: -30